// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvdb_server.proto

package taas_leveldb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpType int32

const (
	OpType_Read   OpType = 0
	OpType_Insert OpType = 1
	OpType_Update OpType = 2
	OpType_Delete OpType = 3
)

var OpType_name = map[int32]string{
	0: "Read",
	1: "Insert",
	2: "Update",
	3: "Delete",
}

var OpType_value = map[string]int32{
	"Read":   0,
	"Insert": 1,
	"Update": 2,
	"Delete": 3,
}

func (x OpType) String() string {
	return proto.EnumName(OpType_name, int32(x))
}

func (OpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e41b8698c00e37fc, []int{0}
}

type KvDBData struct {
	OpType               OpType   `protobuf:"varint,1,opt,name=op_type,json=opType,proto3,enum=proto.OpType" json:"op_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Csn                  uint64   `protobuf:"varint,4,opt,name=csn,proto3" json:"csn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvDBData) Reset()         { *m = KvDBData{} }
func (m *KvDBData) String() string { return proto.CompactTextString(m) }
func (*KvDBData) ProtoMessage()    {}
func (*KvDBData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e41b8698c00e37fc, []int{0}
}

func (m *KvDBData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvDBData.Unmarshal(m, b)
}
func (m *KvDBData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvDBData.Marshal(b, m, deterministic)
}
func (m *KvDBData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvDBData.Merge(m, src)
}
func (m *KvDBData) XXX_Size() int {
	return xxx_messageInfo_KvDBData.Size(m)
}
func (m *KvDBData) XXX_DiscardUnknown() {
	xxx_messageInfo_KvDBData.DiscardUnknown(m)
}

var xxx_messageInfo_KvDBData proto.InternalMessageInfo

func (m *KvDBData) GetOpType() OpType {
	if m != nil {
		return m.OpType
	}
	return OpType_Read
}

func (m *KvDBData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KvDBData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KvDBData) GetCsn() uint64 {
	if m != nil {
		return m.Csn
	}
	return 0
}

type KvDBRequest struct {
	Data                 []*KvDBData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KvDBRequest) Reset()         { *m = KvDBRequest{} }
func (m *KvDBRequest) String() string { return proto.CompactTextString(m) }
func (*KvDBRequest) ProtoMessage()    {}
func (*KvDBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e41b8698c00e37fc, []int{1}
}

func (m *KvDBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvDBRequest.Unmarshal(m, b)
}
func (m *KvDBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvDBRequest.Marshal(b, m, deterministic)
}
func (m *KvDBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvDBRequest.Merge(m, src)
}
func (m *KvDBRequest) XXX_Size() int {
	return xxx_messageInfo_KvDBRequest.Size(m)
}
func (m *KvDBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KvDBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KvDBRequest proto.InternalMessageInfo

func (m *KvDBRequest) GetData() []*KvDBData {
	if m != nil {
		return m.Data
	}
	return nil
}

type KvDBResponse struct {
	Result               bool        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Data                 []*KvDBData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KvDBResponse) Reset()         { *m = KvDBResponse{} }
func (m *KvDBResponse) String() string { return proto.CompactTextString(m) }
func (*KvDBResponse) ProtoMessage()    {}
func (*KvDBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e41b8698c00e37fc, []int{2}
}

func (m *KvDBResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvDBResponse.Unmarshal(m, b)
}
func (m *KvDBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvDBResponse.Marshal(b, m, deterministic)
}
func (m *KvDBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvDBResponse.Merge(m, src)
}
func (m *KvDBResponse) XXX_Size() int {
	return xxx_messageInfo_KvDBResponse.Size(m)
}
func (m *KvDBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KvDBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KvDBResponse proto.InternalMessageInfo

func (m *KvDBResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *KvDBResponse) GetData() []*KvDBData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.OpType", OpType_name, OpType_value)
	proto.RegisterType((*KvDBData)(nil), "proto.KvDBData")
	proto.RegisterType((*KvDBRequest)(nil), "proto.KvDBRequest")
	proto.RegisterType((*KvDBResponse)(nil), "proto.KvDBResponse")
}

func init() {
	proto.RegisterFile("kvdb_server.proto", fileDescriptor_e41b8698c00e37fc)
}

var fileDescriptor_e41b8698c00e37fc = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0x34, 0x69, 0xbe, 0x3a, 0xd5, 0x1a, 0x57, 0x91, 0xe0, 0x29, 0x54, 0x90, 0xe0,
	0x21, 0x42, 0x04, 0xcf, 0x52, 0x0a, 0x45, 0x7a, 0xb0, 0xac, 0x7a, 0xf1, 0x52, 0xb6, 0xcd, 0x1c,
	0xa4, 0x4b, 0xb3, 0xee, 0x4e, 0x16, 0xfa, 0xdf, 0xcb, 0x6e, 0x52, 0xa9, 0x17, 0xf1, 0x34, 0x6f,
	0x66, 0x67, 0x7f, 0xef, 0x0d, 0x9c, 0x6d, 0x6c, 0xb5, 0x5a, 0x1a, 0xd4, 0x16, 0x75, 0xa1, 0x74,
	0x4d, 0x35, 0xeb, 0xfb, 0x32, 0x96, 0x30, 0x98, 0xdb, 0xe9, 0x64, 0x2a, 0x48, 0xb0, 0x1b, 0xf8,
	0x5f, 0xab, 0x25, 0xed, 0x14, 0xa6, 0x41, 0x16, 0xe4, 0xa3, 0xf2, 0xa4, 0xdd, 0x2d, 0x9e, 0xd5,
	0xeb, 0x4e, 0x21, 0x8f, 0x6b, 0x5f, 0x59, 0x02, 0xe1, 0x06, 0x77, 0x69, 0x2f, 0x0b, 0xf2, 0x23,
	0xee, 0x24, 0xbb, 0x80, 0xbe, 0x15, 0xb2, 0xc1, 0x34, 0xf4, 0xb3, 0xb6, 0x71, 0x7b, 0x6b, 0xb3,
	0x4d, 0xa3, 0x2c, 0xc8, 0x23, 0xee, 0xe4, 0xb8, 0x84, 0xa1, 0x73, 0xe3, 0xf8, 0xd9, 0xa0, 0x21,
	0x76, 0x0d, 0x51, 0x25, 0x48, 0xa4, 0x41, 0x16, 0xe6, 0xc3, 0xf2, 0xb4, 0x73, 0xdb, 0xe7, 0xe1,
	0xfe, 0x71, 0x3c, 0x87, 0xe3, 0xf6, 0x8f, 0x51, 0xf5, 0xd6, 0x20, 0xbb, 0x84, 0x58, 0xa3, 0x69,
	0x24, 0xf9, 0x90, 0x03, 0xde, 0x75, 0xdf, 0xb0, 0xde, 0x2f, 0xb0, 0xdb, 0x07, 0x88, 0xdb, 0x63,
	0xd8, 0x00, 0x22, 0x8e, 0xa2, 0x4a, 0xfe, 0x31, 0x80, 0xf8, 0x69, 0x6b, 0x50, 0x53, 0x12, 0x38,
	0xfd, 0xa6, 0x2a, 0x41, 0x98, 0xf4, 0x9c, 0x9e, 0xa2, 0x44, 0xc2, 0x24, 0x2c, 0x1f, 0x61, 0xe4,
	0x48, 0x33, 0xa4, 0x17, 0xd4, 0xf6, 0x63, 0x8d, 0xac, 0x80, 0x70, 0x86, 0xc4, 0xd8, 0x81, 0x4f,
	0x77, 0xd6, 0xd5, 0xf9, 0x8f, 0x59, 0x1b, 0x7b, 0x4f, 0x58, 0x34, 0x87, 0x84, 0x45, 0xf3, 0x77,
	0xc2, 0x24, 0x79, 0x1f, 0x15, 0x77, 0x24, 0x84, 0x59, 0x4a, 0xb4, 0x28, 0xab, 0xd5, 0x2a, 0xf6,
	0x5b, 0xf7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xfd, 0x95, 0x25, 0xdf, 0x01, 0x00, 0x00,
}
