
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/chzyer/readline"
  branch = "master"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.7.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/pingcap/tidb"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/pingcap/tipb"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[override]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.0"

[[override]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.1.0"


[[override]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go.git"
  version = "=1.7.5"

[[override]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  revision = "82921fcf811d228d2fa202bc31238b356bf9f8d5"

[[constraint]]
  name = "github.com/apple/foundationdb"
  version = "5.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"


[prune]
  go-tests = true
  unused-packages = true
  non-go = true