version: '2.1'

services:
  mariadb:
    image: mariadb
    ports:
      - "3308:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
    restart: on-failure

  # monitors
  ycsb:
    image: pingcap/go-ycsb
