version: '2.1'

services:
  pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "test"
    restart: on-failure

  # monitors
  ycsb:
    image: pingcap/go-ycsb
