// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: leveldb.proto

package leveldb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leveldb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_leveldb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_leveldb_proto_rawDescGZIP(), []int{0}
}

func (x *KVPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KVPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LeveldbRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KvPair *KVPair `protobuf:"bytes,2,req,name=kv_pair,json=kvPair" json:"kv_pair,omitempty"`
}

func (x *LeveldbRequest) Reset() {
	*x = LeveldbRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leveldb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeveldbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeveldbRequest) ProtoMessage() {}

func (x *LeveldbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leveldb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeveldbRequest.ProtoReflect.Descriptor instead.
func (*LeveldbRequest) Descriptor() ([]byte, []int) {
	return file_leveldb_proto_rawDescGZIP(), []int{1}
}

func (x *LeveldbRequest) GetKvPair() *KVPair {
	if x != nil {
		return x.KvPair
	}
	return nil
}

type LeveldbResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Value        []byte  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	ErrorMessage *string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (x *LeveldbResponse) Reset() {
	*x = LeveldbResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leveldb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeveldbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeveldbResponse) ProtoMessage() {}

func (x *LeveldbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leveldb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeveldbResponse.ProtoReflect.Descriptor instead.
func (*LeveldbResponse) Descriptor() ([]byte, []int) {
	return file_leveldb_proto_rawDescGZIP(), []int{2}
}

func (x *LeveldbResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *LeveldbResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LeveldbResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_leveldb_proto protoreflect.FileDescriptor

var file_leveldb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x22, 0x30, 0x0a, 0x06, 0x4b, 0x56, 0x50, 0x61,
	0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07,
	0x6b, 0x76, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x2e, 0x4b, 0x56, 0x50, 0x61, 0x69, 0x72, 0x52, 0x06,
	0x6b, 0x76, 0x50, 0x61, 0x69, 0x72, 0x22, 0x66, 0x0a, 0x0f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x64,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc2,
	0x01, 0x0a, 0x0e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3c, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x2e,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x17, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62,
	0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x64,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x17, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x64, 0x62, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64,
	0x62, 0x80, 0x01, 0x01,
}

var (
	file_leveldb_proto_rawDescOnce sync.Once
	file_leveldb_proto_rawDescData = file_leveldb_proto_rawDesc
)

func file_leveldb_proto_rawDescGZIP() []byte {
	file_leveldb_proto_rawDescOnce.Do(func() {
		file_leveldb_proto_rawDescData = protoimpl.X.CompressGZIP(file_leveldb_proto_rawDescData)
	})
	return file_leveldb_proto_rawDescData
}

var file_leveldb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_leveldb_proto_goTypes = []interface{}{
	(*KVPair)(nil),          // 0: leveldb.KVPair
	(*LeveldbRequest)(nil),  // 1: leveldb.LeveldbRequest
	(*LeveldbResponse)(nil), // 2: leveldb.LeveldbResponse
}
var file_leveldb_proto_depIdxs = []int32{
	0, // 0: leveldb.LeveldbRequest.kv_pair:type_name -> leveldb.KVPair
	1, // 1: leveldb.LeveldbService.Execute:input_type -> leveldb.LeveldbRequest
	1, // 2: leveldb.LeveldbService.Put:input_type -> leveldb.LeveldbRequest
	1, // 3: leveldb.LeveldbService.Get:input_type -> leveldb.LeveldbRequest
	2, // 4: leveldb.LeveldbService.Execute:output_type -> leveldb.LeveldbResponse
	2, // 5: leveldb.LeveldbService.Put:output_type -> leveldb.LeveldbResponse
	2, // 6: leveldb.LeveldbService.Get:output_type -> leveldb.LeveldbResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_leveldb_proto_init() }
func file_leveldb_proto_init() {
	if File_leveldb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leveldb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leveldb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeveldbRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leveldb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeveldbResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leveldb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leveldb_proto_goTypes,
		DependencyIndexes: file_leveldb_proto_depIdxs,
		MessageInfos:      file_leveldb_proto_msgTypes,
	}.Build()
	File_leveldb_proto = out.File
	file_leveldb_proto_rawDesc = nil
	file_leveldb_proto_goTypes = nil
	file_leveldb_proto_depIdxs = nil
}
