// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: storage.proto

package taas_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoragePullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochId  uint64 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	SendNode *Node  `protobuf:"bytes,2,opt,name=send_node,json=sendNode,proto3" json:"send_node,omitempty"`
	RecvNode *Node  `protobuf:"bytes,3,opt,name=recv_node,json=recvNode,proto3" json:"recv_node,omitempty"`
}

func (x *StoragePullRequest) Reset() {
	*x = StoragePullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoragePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePullRequest) ProtoMessage() {}

func (x *StoragePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePullRequest.ProtoReflect.Descriptor instead.
func (*StoragePullRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StoragePullRequest) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *StoragePullRequest) GetSendNode() *Node {
	if x != nil {
		return x.SendNode
	}
	return nil
}

func (x *StoragePullRequest) GetRecvNode() *Node {
	if x != nil {
		return x.RecvNode
	}
	return nil
}

type StoragePullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   Result         `protobuf:"varint,1,opt,name=result,proto3,enum=taas_proto.Result" json:"result,omitempty"`
	EpochId  uint64         `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	TxnNum   uint64         `protobuf:"varint,3,opt,name=txn_num,json=txnNum,proto3" json:"txn_num,omitempty"`
	Txns     []*Transaction `protobuf:"bytes,4,rep,name=txns,proto3" json:"txns,omitempty"`
	SendNode *Node          `protobuf:"bytes,5,opt,name=send_node,json=sendNode,proto3" json:"send_node,omitempty"`
	RecvNode *Node          `protobuf:"bytes,6,opt,name=recv_node,json=recvNode,proto3" json:"recv_node,omitempty"`
}

func (x *StoragePullResponse) Reset() {
	*x = StoragePullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoragePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePullResponse) ProtoMessage() {}

func (x *StoragePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePullResponse.ProtoReflect.Descriptor instead.
func (*StoragePullResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StoragePullResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_Fail
}

func (x *StoragePullResponse) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *StoragePullResponse) GetTxnNum() uint64 {
	if x != nil {
		return x.TxnNum
	}
	return 0
}

func (x *StoragePullResponse) GetTxns() []*Transaction {
	if x != nil {
		return x.Txns
	}
	return nil
}

func (x *StoragePullResponse) GetSendNode() *Node {
	if x != nil {
		return x.SendNode
	}
	return nil
}

func (x *StoragePullResponse) GetRecvNode() *Node {
	if x != nil {
		return x.RecvNode
	}
	return nil
}

type StoragePushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   Result         `protobuf:"varint,1,opt,name=result,proto3,enum=taas_proto.Result" json:"result,omitempty"`
	EpochId  uint64         `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	TxnNum   uint64         `protobuf:"varint,3,opt,name=txn_num,json=txnNum,proto3" json:"txn_num,omitempty"`
	Txns     []*Transaction `protobuf:"bytes,4,rep,name=txns,proto3" json:"txns,omitempty"`
	SendNode *Node          `protobuf:"bytes,5,opt,name=send_node,json=sendNode,proto3" json:"send_node,omitempty"`
	RecvNode *Node          `protobuf:"bytes,6,opt,name=recv_node,json=recvNode,proto3" json:"recv_node,omitempty"`
}

func (x *StoragePushResponse) Reset() {
	*x = StoragePushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoragePushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePushResponse) ProtoMessage() {}

func (x *StoragePushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePushResponse.ProtoReflect.Descriptor instead.
func (*StoragePushResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StoragePushResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_Fail
}

func (x *StoragePushResponse) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *StoragePushResponse) GetTxnNum() uint64 {
	if x != nil {
		return x.TxnNum
	}
	return 0
}

func (x *StoragePushResponse) GetTxns() []*Transaction {
	if x != nil {
		return x.Txns
	}
	return nil
}

func (x *StoragePushResponse) GetSendNode() *Node {
	if x != nil {
		return x.SendNode
	}
	return nil
}

func (x *StoragePushResponse) GetRecvNode() *Node {
	if x != nil {
		return x.RecvNode
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

var file_storage_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x12, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x72,
	0x65, 0x63, 0x76, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x63, 0x76, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x80, 0x02, 0x0a, 0x13, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x6e,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x78, 0x6e, 0x4e,
	0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x78, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x74, 0x78, 0x6e, 0x73, 0x12,
	0x2d, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2d,
	0x0a, 0x09, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x08, 0x72, 0x65, 0x63, 0x76, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x80, 0x02,
	0x0a, 0x13, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x78, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74,
	0x78, 0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x78, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x74, 0x78,
	0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x2d, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x72, 0x65, 0x63, 0x76, 0x4e, 0x6f, 0x64, 0x65,
	0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x74, 0x61, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData = file_storage_proto_rawDesc
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_proto_rawDescData)
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_storage_proto_goTypes = []interface{}{
	(*StoragePullRequest)(nil),  // 0: taas_proto.StoragePullRequest
	(*StoragePullResponse)(nil), // 1: taas_proto.StoragePullResponse
	(*StoragePushResponse)(nil), // 2: taas_proto.StoragePushResponse
	(*Node)(nil),                // 3: taas_proto.Node
	(Result)(0),                 // 4: taas_proto.Result
	(*Transaction)(nil),         // 5: taas_proto.Transaction
}
var file_storage_proto_depIdxs = []int32{
	3,  // 0: taas_proto.StoragePullRequest.send_node:type_name -> taas_proto.Node
	3,  // 1: taas_proto.StoragePullRequest.recv_node:type_name -> taas_proto.Node
	4,  // 2: taas_proto.StoragePullResponse.result:type_name -> taas_proto.Result
	5,  // 3: taas_proto.StoragePullResponse.txns:type_name -> taas_proto.Transaction
	3,  // 4: taas_proto.StoragePullResponse.send_node:type_name -> taas_proto.Node
	3,  // 5: taas_proto.StoragePullResponse.recv_node:type_name -> taas_proto.Node
	4,  // 6: taas_proto.StoragePushResponse.result:type_name -> taas_proto.Result
	5,  // 7: taas_proto.StoragePushResponse.txns:type_name -> taas_proto.Transaction
	3,  // 8: taas_proto.StoragePushResponse.send_node:type_name -> taas_proto.Node
	3,  // 9: taas_proto.StoragePushResponse.recv_node:type_name -> taas_proto.Node
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_transaction_proto_init()
	file_node_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoragePullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoragePullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoragePushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_rawDesc = nil
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
